### ISSUE TITLE
Issue of new version

### ISSUE THREAD

**Issue by lichman0405** [kevinshen56714/emc-pypi#10]
emc-pypi is installed by using pip, version is 2022.8.1.1

I run [pmd] (https://github.com/Ramprasad-Group/Polymer-Molecular-Dynamics/tree/v1.4.13)

It reports error:
Info: reading script from "./system.esh"
Undefined subroutine &EMC::IO::open called at /root/miniconda3/lib/python3.8/site-packages/pyemc/emc/scripts/emc_setup.pl line 2886.
Error: core/format.c:359 FormatOpen:
       Error opening file "build.emc".
       Program aborted.

How could I solve it?

**Comment by yigegudaye** [comment]
hi, I meet the same problem with you? Have you solved it?

**Comment by lichman0405** [comment]
> hi, I meet the same problem with you? Have you solved it?

not yet. :(

**Comment by yigegudaye** [comment]
maybe you can refer to this link: https://matsci.org/t/error-with-emc-setup-pl/44153
it seems the new version has some problems

**Comment by kevinshen56714** [comment]
I updated the version. Please update the package and it should work as intended.
